const items = [
  {
    sku: "SKU-1",
    itemName: "Description 1",
    vendor: "Vendor 1",
    uom: "PK",
    qty: 12,
    category: "Category 1",
    cost: 12.5,
  },
  {
    sku: "SKU-2",
    itemName: "Description 2",
    vendor: "Vendor 2",
    uom: "EA",
    qty: 1,
    category: "Category 2",
    cost: 18,
  },
  {
    sku: "SKU-3",
    itemName: "Description 3",
    vendor: "Vendor 3",
    uom: "PK",
    qty: 15,
    category: "Category 3",
    cost: 22.75,
  },
  {
    sku: "SKU-4",
    itemName: "Description 4",
    vendor: "Vendor 1",
    uom: "EA",
    qty: 1,
    category: "Category 1",
    cost: 9.5,
  },
  {
    sku: "SKU-5",
    itemName: "Description 5",
    vendor: "Vendor 2",
    uom: "PK",
    qty: 12,
    category: "Category 2",
    cost: 15.25,
  },
  {
    sku: "SKU-6",
    itemName: "Description 6",
    vendor: "Vendor 3",
    uom: "EA",
    qty: 1,
    category: "Category 3",
    cost: 30,
  },
  {
    sku: "SKU-7",
    itemName: "Description 7",
    vendor: "Vendor 1",
    uom: "PK",
    qty: 15,
    category: "Category 1",
    cost: 11.99,
  },
  {
    sku: "SKU-8",
    itemName: "Description 8",
    vendor: "Vendor 2",
    uom: "EA",
    qty: 1,
    category: "Category 2",
    cost: 24.5,
  },
  {
    sku: "SKU-9",
    itemName: "Description 9",
    vendor: "Vendor 3",
    uom: "PK",
    qty: 12,
    category: "Category 3",
    cost: 17.75,
  },
  {
    sku: "SKU-10",
    itemName: "Description 10",
    vendor: "Vendor 1",
    uom: "EA",
    qty: 1,
    category: "Category 1",
    cost: 28,
  },
];